Add skeleton to dev
blockofmagic/front pull request #2
Opened 2020-10-09 08:14 UTC by pinterid

**Checklist:**

 

-   [x] Have you added an explanation of what your changes do and why you'd like them to be included?
-   [x] Have you updated or added documentation for the change?
-   [x] Have you tested your changes with successful results?

**Type of Changes:**

 

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Documentation (non-breaking change which adds documentation)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**

- Currently there is no react app. #1

**What is the new behavior (if this is a feature change)?**

- Now there is an react app. #1 

**Other information**:

- Ref: https://decembersoft.com/posts/starting-a-react-redux-project-with-typescript/

2020-10-09 08:22 UTC, UnknownExecute commented on src/components/pages/HomePage/index.tsx
> + * Copyright © 2019-2020 Simon Prast
Change Simon Prast to Nico Schett

2020-10-09 08:23 UTC, UnknownExecute approved these changes
Looks good to merge

2020-10-09 08:43 UTC, schettn requested changes
Looks good after few changes. Furthermore have a look at all legacy files like `src/logo.svg.

2020-10-09 08:43 UTC, schettn commented on .gitignore
> +# Copyright © Nico Schett
newline missing
```suggestion
# Copyright © Nico Schett

```

2020-10-09 08:43 UTC, schettn commented on package.json
> +    "@testing-library/user-event": "^7.1.2",
Those should be moved to the dev dependencies.

2020-10-09 08:43 UTC, schettn commented on src/App.test.tsx
> +  expect(linkElement).toBeInTheDocument();
The test case is no longer valid. We should remove it for now.

2020-10-09 08:43 UTC, schettn commented on src/components/atoms/ScrollToTop/index.ts
> +//> Default Component
```suggestion
```
 This is fucking unnecessary. I suggest to remove it form **all** files.

2020-10-22 16:34 UTC, schettn approved these changes
lgtm

2020-10-22 16:42 UTC, merged